config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :coments
  end

  

   root 'posts#index'

end

app/models/coment.rb
class Coment < ActiveRecord::Base
	belongs_to :post

	validates_presence_of :post_id
	validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :coments, dependent: :destroy

	validates_presence_of :title
	validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  before_action :set_coment, only: [:show, :edit, :update, :destroy]

  # GET /coments
  # GET /coments.json
  def index
    @coments = Coment.all
  end

  # GET /coments/1
  # GET /coments/1.json
  def show
  end

  # GET /coments/new
  def new
    @coment = Coment.new
  end

  # GET /coments/1/edit
  def edit
  end

  # POST /coments
  # POST /coments.json
  def create
    @post=Post.find(params[:post_id])#Parametro a buscar en tabla post
    @coment = @post.coments.create(coment_params)

    respond_to do |format|
      if @coment.save
        format.html { redirect_to @post, notice: 'Coment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coment }
        format.js   #create.js.erb This is the File "AJAX"
      else
        format.html { render action: 'new' }
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coments/1
  # PATCH/PUT /coments/1.json
  def update
    respond_to do |format|
      if @coment.update(coment_params)
        format.html { redirect_to @coment, notice: 'Coment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coments/1
  # DELETE /coments/1.json
  def destroy
    @coment.destroy
    respond_to do |format|
      format.html { redirect_to coments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coment
      @coment = Coment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coment_params
      params.require(:coment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name=="admin" && password == "secret"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/coments/_comment.html.erb
<!-- This is the file that  the Object Ajax load  -->
<%= div_for coment do %>
    <p>
	   <strong>Posted <%= time_ago_in_words(coment.created_at)%></strong><br />
	   <%= h(coment.body) %>
    </p>
<% end %>

app/views/coments/_form.html.erb
<%= form_for(@coment) do |f| %>
  <% if @coment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coment.errors.count, "error") %> prohibited this coment from being saved:</h2>

      <ul>
      <% @coment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coments/create.js.erb
var new_coment=$("<%=escape_javascript(render(:partial => @coment)) %>").hide();
$('#comments').prepend(new_coment);
$('#comment_<%= @coment.id%>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/coments/edit.html.erb
<h1>Editing coment</h1>

<%= render 'form' %>

<%= link_to 'Show', @coment %> |
<%= link_to 'Back', coments_path %>

app/views/coments/index.html.erb
<h1>Listing coments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coments.each do |coment| %>
      <tr>
        <td><%= coment.post_id %></td>
        <td><%= coment.body %></td>
        <td><%= link_to 'Show', coment %></td>
        <td><%= link_to 'Edit', edit_coment_path(coment) %></td>
        <td><%= link_to 'Destroy', coment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coment', new_coment_path %>

app/views/coments/new.html.erb
<h1>New coment</h1>

<%= render 'form' %>

<%= link_to 'Back', coments_path %>

app/views/coments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @coment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @coment.body %>
</p>

<%= link_to 'Edit', edit_coment_path(@coment) %> |
<%= link_to 'Back', coments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<h2>Comments</h2>
<div id="comments">
	<%= @post.coments.each do |comment| %>
		<%= div_for comment do %>
			<p>
				<strong>Posted <%= time_ago_in_words(comment.created_at)%></strong><br />
				<%= h(comment.body) %>
			</p>
		<% end %>
	<% end %>
</div>

<%= form_for([@post, Coment.new], remote: true) do |f| %> 
	<p> 
		<%= f.label :body, "New Cooment" %> <br />
		<%= f.text_area :body%>
	</p>
	<p><%= f.submit "Add Coomment"%></p>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>